/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:4f9ce40b74ddf1ae708cb2baa6de36ae:cabb6e7a9041e9548d7377f0ad41841d:ef1cac96799ed34d4bd4902a045de962$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class EnemyDeathAnimationProject
	{
		public const string BlueShipDeathAnimationPNGs_000 = "BlueShipDeathAnimationPNGs_000";
		public const string BlueShipDeathAnimationPNGs_001 = "BlueShipDeathAnimationPNGs_001";
		public const string BlueShipDeathAnimationPNGs_002 = "BlueShipDeathAnimationPNGs_002";
		public const string BlueShipDeathAnimationPNGs_003 = "BlueShipDeathAnimationPNGs_003";
		public const string BlueShipDeathAnimationPNGs_004 = "BlueShipDeathAnimationPNGs_004";
		public const string BlueShipDeathAnimationPNGs_005 = "BlueShipDeathAnimationPNGs_005";
		public const string BlueShipDeathAnimationPNGs_006 = "BlueShipDeathAnimationPNGs_006";
		public const string BlueShipDeathAnimationPNGs_007 = "BlueShipDeathAnimationPNGs_007";
		public const string BlueShipDeathAnimationPNGs_008 = "BlueShipDeathAnimationPNGs_008";
		public const string BlueShipDeathAnimationPNGs_009 = "BlueShipDeathAnimationPNGs_009";
		public const string BlueShipDeathAnimationPNGs_010 = "BlueShipDeathAnimationPNGs_010";
		public const string BlueShipDeathAnimationPNGs_011 = "BlueShipDeathAnimationPNGs_011";
		public const string BlueShipDeathAnimationPNGs_012 = "BlueShipDeathAnimationPNGs_012";
		public const string BlueShipDeathAnimationPNGs_013 = "BlueShipDeathAnimationPNGs_013";
		public const string BlueShipDeathAnimationPNGs_014 = "BlueShipDeathAnimationPNGs_014";
		public const string BlueShipDeathAnimationPNGs_015 = "BlueShipDeathAnimationPNGs_015";
		public const string BlueShipDeathAnimationPNGs_016 = "BlueShipDeathAnimationPNGs_016";
		public const string BlueShipDeathAnimationPNGs_017 = "BlueShipDeathAnimationPNGs_017";
		public const string BlueShipDeathAnimationPNGs_018 = "BlueShipDeathAnimationPNGs_018";
		public const string BlueShipDeathAnimationPNGs_019 = "BlueShipDeathAnimationPNGs_019";
		public const string BlueShipDeathAnimationPNGs_020 = "BlueShipDeathAnimationPNGs_020";
		public const string BlueShipDeathAnimationPNGs_021 = "BlueShipDeathAnimationPNGs_021";
		public const string BlueShipDeathAnimationPNGs_022 = "BlueShipDeathAnimationPNGs_022";
		public const string BlueShipDeathAnimationPNGs_023 = "BlueShipDeathAnimationPNGs_023";
		public const string BlueShipDeathAnimationPNGs_024 = "BlueShipDeathAnimationPNGs_024";
		public const string BlueShipDeathAnimationPNGs_025 = "BlueShipDeathAnimationPNGs_025";
		public const string BlueShipDeathAnimationPNGs_026 = "BlueShipDeathAnimationPNGs_026";
		public const string BlueShipDeathAnimationPNGs_027 = "BlueShipDeathAnimationPNGs_027";
		public const string BlueShipDeathAnimationPNGs_028 = "BlueShipDeathAnimationPNGs_028";
		public const string BlueShipDeathAnimationPNGs_029 = "BlueShipDeathAnimationPNGs_029";
		public const string BlueShipDeathAnimationPNGs_030 = "BlueShipDeathAnimationPNGs_030";
		public const string BlueShipDeathAnimationPNGs_031 = "BlueShipDeathAnimationPNGs_031";
		public const string BlueShipDeathAnimationPNGs_032 = "BlueShipDeathAnimationPNGs_032";
		public const string BlueShipDeathAnimationPNGs_033 = "BlueShipDeathAnimationPNGs_033";
		public const string BlueShipDeathAnimationPNGs_034 = "BlueShipDeathAnimationPNGs_034";
		public const string BlueShipDeathAnimationPNGs_035 = "BlueShipDeathAnimationPNGs_035";
		public const string BlueShipDeathAnimationPNGs_036 = "BlueShipDeathAnimationPNGs_036";
		public const string BlueShipDeathAnimationPNGs_037 = "BlueShipDeathAnimationPNGs_037";
		public const string BlueShipDeathAnimationPNGs_038 = "BlueShipDeathAnimationPNGs_038";
		public const string BlueShipDeathAnimationPNGs_039 = "BlueShipDeathAnimationPNGs_039";
		public const string BlueShipDeathAnimationPNGs_040 = "BlueShipDeathAnimationPNGs_040";
		public const string BlueShipDeathAnimationPNGs_041 = "BlueShipDeathAnimationPNGs_041";
		public const string BlueShipDeathAnimationPNGs_042 = "BlueShipDeathAnimationPNGs_042";
		public const string BlueShipDeathAnimationPNGs_043 = "BlueShipDeathAnimationPNGs_043";
		public const string BlueShipDeathAnimationPNGs_044 = "BlueShipDeathAnimationPNGs_044";
		public const string BlueShipDeathAnimationPNGs_045 = "BlueShipDeathAnimationPNGs_045";
		public const string BlueShipDeathAnimationPNGs_046 = "BlueShipDeathAnimationPNGs_046";
		public const string BlueShipDeathAnimationPNGs_047 = "BlueShipDeathAnimationPNGs_047";
		public const string BlueShipDeathAnimationPNGs_048 = "BlueShipDeathAnimationPNGs_048";
		public const string BlueShipDeathAnimationPNGs_049 = "BlueShipDeathAnimationPNGs_049";
		public const string BlueShipDeathAnimationPNGs_050 = "BlueShipDeathAnimationPNGs_050";
		public const string BlueShipDeathAnimationPNGs_051 = "BlueShipDeathAnimationPNGs_051";
		public const string BlueShipDeathAnimationPNGs_052 = "BlueShipDeathAnimationPNGs_052";
		public const string BlueShipDeathAnimationPNGs_053 = "BlueShipDeathAnimationPNGs_053";
		public const string BlueShipDeathAnimationPNGs_054 = "BlueShipDeathAnimationPNGs_054";
		public const string BlueShipDeathAnimationPNGs_055 = "BlueShipDeathAnimationPNGs_055";
		public const string BlueShipDeathAnimationPNGs_056 = "BlueShipDeathAnimationPNGs_056";
		public const string BlueShipDeathAnimationPNGs_057 = "BlueShipDeathAnimationPNGs_057";
		public const string BlueShipDeathAnimationPNGs_058 = "BlueShipDeathAnimationPNGs_058";
		public const string BlueShipDeathAnimationPNGs_059 = "BlueShipDeathAnimationPNGs_059";
		public const string BlueShipDeathAnimationPNGs_060 = "BlueShipDeathAnimationPNGs_060";
		public const string BlueShipDeathAnimationPNGs_061 = "BlueShipDeathAnimationPNGs_061";
	}
}